config/routes.rb
Rails.application.routes.draw do
  resources :kinsta_escapes, only: [:new, :create]
  resources :screaming_frogs, only: [:new, :create]
  resources :safe_redirect_managers, only: [:new, :create]
end

app/models/kinsta_escape.rb
require 'csv'

class KinstaEscape
  include ActiveModel::Model

  attr_accessor :content
  attr_reader :sanitized_rows

  validates :content, presence: true

  def prepare
    return unless valid?
    @sanitized_rows = sanitize(csv: content)
  end

  private

  def sanitize(csv:)
    rows = CSV.parse(csv)

    rows = rows.reject do |row|
      row.size != 4
    end

    rows = rows.reject do |row|
      row.third.include? "?"
    end

    rows = rows.reject do |row|
      row&.third.include? ","
    end

    rows = rows.reject do |row|
      row&.fourth.include? ","
    end

    # Escape `redirect_from`
    rows = rows.map do |row|
      row[2] = row.third.tr('"', '')
      row[2] = row.third.chomp("/")
      row[2] = row.third + "/?"

      row[2] = '^' + row.third + '$'

      row
    end

    # Escape `redirect_from`
    froms = rows.map(&:third)
    rows.reject do |row|
      froms.count(row.third) > 1
    end
  end
end

app/models/preparation.rb
require 'csv'

class Preparation
  include ActiveModel::Model

  attr_accessor :content
  attr_reader :sanitized_rows

  validates :content, presence: true

  FILE_EXTENSION = %w(
    .png
    .mp4
    .mp3
    .bmp
    .gif
    .jpeg
    .svg
    .mp4
    .jpg
    .jpeg
    .pdf
    .zip
    .rar
  )

  def prepare
    return unless valid?
    @sanitized_rows = sanitize(csv: content)
  end

  private

  def sanitize(csv:)
    rows = CSV.parse(csv)

    # Remove screaming frog non-sense title and CSV headers
    rows.shift(2)

    addresses = rows.map(&:first)

    # Filter out file URLs
    addresses = addresses.reject do |address|
      address.split("?").first.end_with? *FILE_EXTENSION
    end

    # Remove domains and duplicates
    addresses = addresses.map do |address|
      Domainatrix.parse(address).path
    end.uniq

    # Sort "?"
    addresses = addresses.sort.partition do |address|
      address.split("?").second.blank?
    end.reverse.flatten

    rows = addresses.map do |source|
      [source, "", "0", "301", "0"]
    end

    rows.unshift(%w(source target regex code order))
  end
end

app/models/safe_redirect_manager.rb
require 'csv'

class SafeRedirectManager
  include ActiveModel::Model

  attr_accessor :content
  attr_reader :sanitized_rows

  validates :content, presence: true

  def prepare
    return unless valid?
    @sanitized_rows = sanitize(csv: content)
  end

  private

  def sanitize(csv:)
    rows = CSV.parse(csv)

    # Remove safe redirection manager header
    header = rows.shift(1).first

    # Normalize rows
    rows = rows.map do |row|
      row.map do |element|
        element.tr('"', '')
      end
    end

    # Remove empty source or empty target
    rows = rows.reject do |row|
      row.first.blank? || row.second.blank?
    end

    # Remove level-1 redirection loop
    rows = rows.reject do |row|
      row.first&.chomp("/") == row.second&.chomp("/")
    end

    # Add back header
    rows.unshift(header)

    # Normalize rows
    rows = rows.map do |row|
      row.map do |element|
        '"' + element.tr('"', '') + '"'
      end
    end
  end
end

app/models/screaming_frog.rb
require 'csv'

class ScreamingFrog
  include ActiveModel::Model

  attr_accessor :content
  attr_reader :sanitized_rows

  validates :content, presence: true

  FILE_EXTENSION = %w(
    .png
    .mp4
    .mp3
    .bmp
    .gif
    .jpeg
    .svg
    .mp4
    .jpg
    .jpeg
    .pdf
    .zip
    .rar
  )

  def prepare
    return unless valid?
    @sanitized_rows = sanitize(csv: content)
  end

  private

  def sanitize(csv:)
    rows = CSV.parse(csv)

    # Remove screaming frog non-sense title and CSV headers
    rows.shift(2)

    addresses = rows.map(&:first)

    # Filter out empty lines
    addresses = addresses.reject do |address|
      address.blank?
    end

    # Filter out file URLs
    addresses = addresses.reject do |address|
      address.split("?").first.end_with? *FILE_EXTENSION
    end

    # Remove domains and duplicates
    addresses = addresses.map do |address|
      Domainatrix.parse(address).path
    end.uniq

    # Sort "?"
    addresses = addresses.sort.partition do |address|
      address.split("?").second.blank?
    end.reverse.flatten

    rows = addresses.map do |source|
      ['"' + source + '"', '""', '"0"', '"301"', '"0"']
    end

    rows.unshift(%w("source" "target" "regex" "code" "order"))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kinsta_escapes_controller.rb
class KinstaEscapesController < ApplicationController
  def new
    @kinsta_escape = KinstaEscape.new
  end

  def create
    @kinsta_escape = KinstaEscape.new(kinsta_escape_params)

    if @kinsta_escape.prepare
      flash[:success] = "Success!"
      render :new
    else
      flash[:error] = "What have you done, boy?"
      render :new
    end
  end

  private

  def kinsta_escape_params
    params.require(:kinsta_escape).permit(:content)
  end
end

app/controllers/safe_redirect_managers_controller.rb
class SafeRedirectManagersController < ApplicationController
  def new
    @safe_redirect_manager = SafeRedirectManager.new
  end

  def create
    @safe_redirect_manager = SafeRedirectManager.new(safe_redirect_manager_params)

    if @safe_redirect_manager.prepare
      flash[:success] = "Success!"
      render :new
    else
      flash[:error] = "What have you done, boy?"
      render :new
    end
  end

  private

  def safe_redirect_manager_params
    params.require(:safe_redirect_manager).permit(:content)
  end
end

app/controllers/screaming_frogs_controller.rb
class ScreamingFrogsController < ApplicationController
  # GET /screaming_frogs/new
  def new
    @screaming_frog = ScreamingFrog.new
  end

  # POST /screaming_frogs
  def create
    @screaming_frog = ScreamingFrog.new(screaming_frog_params)

    if @screaming_frog.prepare
      flash[:success] = "Success!"
      render :new
    else
      flash[:error] = "What have you done, boy?"
      render :new
    end
  end

  private
    # Only allow a trusted parameter "white list" through.
    def screaming_frog_params
      params.require(:screaming_frog).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/kinsta_escapes/_form.html.erb
<%= form_with(model: kinsta_escape, local: true, method: :post) do |form| %>
  <% if kinsta_escape.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kinsta_escape.errors.count, "error") %> prohibited this kinsta_escape from being saved:</h2>

      <ul>
      <% kinsta_escape.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content, 'Kinsta CSV' %>
    <br/>
    <%= form.text_area :content, cols: 150, rows: 40, required: 'required' %>
  </div>

  <div class="actions">
    <%= form.submit 'Escape' %>
  </div>
<% end %>

app/views/kinsta_escapes/new.html.erb
<h1>Escape Kinsta CSV</h1>

<% flash.each do |name, msg| -%>
  <%= content_tag :h2, msg, class: name %>
<% end -%>

<hr/>

<%= render 'form', kinsta_escape: @kinsta_escape %>

<hr/>

<% if @kinsta_escape.sanitized_rows %>
  <textarea cols="150" rows="40" readonly="readonly">
    <% @kinsta_escape.sanitized_rows.each do |row| %>
<%= row.join(",") + "\r\n" -%>
    <% end -%>
  </textarea>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CsvPreparation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>CSV Preparation</h1>

<h2><%= link_to "Step 1", new_screaming_frog_path %></h2>
<p>Transform your Screaming Frog CSV into Safe Redirect Manager format.</p>
<ul>
  <li>first 2 rows will be stripped because they are Screaming Frog headers</li>
  <li>only the first column is important, anything else will be stripped</li>
  <li>domains in the first column will be stripped</li>
  <li>duplicated <code>source</code> will be stripped</li>
  <li><code>target</code> defaults to empty string</li>
  <li><code>regex</code> defaults to <code>0</code></li>
  <li><code>code</code> defaults to <code>301</code></li>
  <li><code>order</code> defaults to <code>0</code></li>
</ul>

<hr/>

<h2><%= link_to "Step 2", new_safe_redirect_manager_path %></h2>
<p>Sanitize your Safe Redirect Manager CSV.</p>
<ul>
  <li>first row must be the headers, i.e: <code>"source","target","regex","code","order"</code></li>
  <li>level-1 redirection loop will be stripped, i.e: <code>/about --> /about/</code> & <code>/about/ --> /about</code> & <code>/about --> /about</code></li>
  <li>empty <code>source</code> will be stripped</li>
  <li>empty <code>target</code> will be stripped</li>
</ul>

<hr/>

<h2>Step 3</h2>
<p>Import the sanitized CSV via <%= link_to "srm-importer", "https://github.com/ItinerisLtd/srm-importer" %> (wp-admin &raquo; Tool &raquo; SRM Importer)</p>
<p>Ask the dev team if it is not installed.</p>
<p>Too many redirect rules will slow down the site, aim for less than 250 rules!</p>
<p>Use Kinsta Nginx redirection whenever possible.</p>

<hr/>

<h2>Developer Only: <%= link_to "Escape Kinsta-exported CSV", new_kinsta_escape_path %></h2>
<p>Escape your Kinsta-exported CSV.</p>
<ul>
  <li>Example 1 - Before: <code>/about</code></li>
  <li>Example 1 - After: <code>^/about/?$</code></li>
  <li>Example 2 - Before: <code>/about/</code></li>
  <li>Example 2 - After: <code>^/about/?$</code></li>
</ul>
<p>Due to Kinsta and Nginx limitations, these rows will be stripped:</p>
<ul>
  <li>not 4 columns</li>
  <li><code>redirection_from</code> containing question marks</li>
  <li><code>redirection_from</code> containing commas</li>
  <li><code>redirection_to</code> containing commas</li>
  <li>if duplicated <code>redirection_from</code> (after escape) found, both rows will be stripped</li>
</ul>

app/views/preparations/_form.html.erb
<%= form_with(model: preparation, local: true, method: :post) do |form| %>
  <% if preparation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(preparation.errors.count, "error") %> prohibited this preparation from being saved:</h2>

      <ul>
      <% preparation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content, 'Screaming Frog CSV' %>
    <br/>
    <%= form.text_area :content, cols: 150, rows: 40 %>
  </div>

  <br/>

  <div class="actions">
    <%= form.submit 'Sanitize' %>
  </div>
<% end %>

app/views/preparations/new.html.erb
<h1>New Preparation</h1>

<% flash.each do |name, msg| -%>
  <%= content_tag :h2, msg, class: name %>
<% end -%>

<hr/>

<%= render 'form', preparation: @preparation %>

<hr/>

<% if @preparation.sanitized_rows %>
  <textarea cols="150" rows="40">
    <% @preparation.sanitized_rows.each do |row| %>
<%= row.join(",") + "\r\n" -%>
    <% end -%>
  </textarea>
<% end %>

app/views/safe_redirect_managers/_form.html.erb
<%= form_with(model: safe_redirect_manager, local: true, method: :post) do |form| %>
  <% if safe_redirect_manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(safe_redirect_manager.errors.count, "error") %> prohibited this safe_redirect_manager from being saved:</h2>

      <ul>
      <% safe_redirect_manager.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content, 'Safe Redirect Manager CSV' %>
    <br/>
    <%= form.text_area :content, cols: 150, rows: 40, required: 'required' %>
  </div>

  <div class="actions">
    <%= form.submit 'Sanitize' %>
  </div>
<% end %>

app/views/safe_redirect_managers/new.html.erb
<h1>Sanitize Safe Redirect Manager CSV</h1>

<% flash.each do |name, msg| -%>
  <%= content_tag :h2, msg, class: name %>
<% end -%>

<hr/>

<%= render 'form', safe_redirect_manager: @safe_redirect_manager %>

<hr/>

<% if @safe_redirect_manager.sanitized_rows %>
  <textarea cols="150" rows="40" readonly="readonly">
    <% @safe_redirect_manager.sanitized_rows.each do |row| %>
<%= row.join(",") + "\r\n" -%>
    <% end -%>
  </textarea>
<% end %>

app/views/screaming_frogs/_form.html.erb
<%= form_with(model: screaming_frog, local: true, method: :post) do |form| %>
  <% if screaming_frog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(screaming_frog.errors.count, "error") %> prohibited this screaming_frog from being saved:</h2>

      <ul>
      <% screaming_frog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content, 'Screaming Frog CSV' %>
    <br/>
    <%= form.text_area :content, cols: 150, rows: 40, required: 'required' %>
  </div>

  <br/>

  <div class="actions">
    <%= form.submit 'Transform' %>
  </div>
<% end %>

app/views/screaming_frogs/new.html.erb
<h1>Transform Screaming Frog CSV</h1>

<% flash.each do |name, msg| -%>
  <%= content_tag :h2, msg, class: name %>
<% end -%>

<hr/>

<%= render 'form', screaming_frog: @screaming_frog %>

<hr/>

<% if @screaming_frog.sanitized_rows %>
  <textarea cols="150" rows="40" readonly="readonly">
    <% @screaming_frog.sanitized_rows.each do |row| %>
<%= row.join(",") + "\r\n" -%>
    <% end -%>
  </textarea>
<% end %>